compatibility_date = "2022-02-03"
main = "./dist/worker.ts"
name = "jkot-turtles"

[durable_objects]
bindings = [
  {name = "TUTLE_GAME_DO", class_name = "TurtleGame"},
]

[[migrations]]
new_classes = ["TurtleGame"]
tag = "v1"
